version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: hoanguyencoder
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db_hoanguyencoder
    ports:
      - "5432:5432"
    volumes:
      - example-db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./BackEnd/app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - DB_NAME=db_hoanguyencoder
      - DB_USERNAME=hoanguyencoder
      - DB_PASSWORD=12345678
      - DB_HOSTNAME=postgres
    depends_on:
      - postgres

  nginx:
    build:
      context: ./FrontEnd 
      dockerfile: DockerfileNginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  example-db:
    

    