version: '3'
services:
  frontend:
    build:
      context: ./FrontEnd/vue-basic
      dockerfile: ../DockerfileNginx
    ports:
      - "8080:8080"
    volumes:
      - ./FrontEnd/vue-basic:/vue-basic
      - /vue-basic/node_modules
    environment:
      - NODE_ENV=production

  nginx:
    container_name: vue-nginx
    image: nginx:alpine  # Use Nginx to serve the built app
    ports:
      - "80:80"  # Expose port 80 for the NGINX server
    volumes:
      - ./FrontEnd/nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom nginx config
      - ./FrontEnd/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount custom default config
      - ./FrontEnd/vue-basic/dist:/usr/share/nginx/html  # Mount the built Vue.js app to NGINX
    depends_on:
      - frontend  # Ensure 'app' service runs before 'nginx'